import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="flex flex-col min-h-screen">
					<Header 
						logoText="Next.js Boilerplate"
						items={[
							{ label: "ホーム", href: "/" },
							{ label: "自己紹介", href: "/about" },
							{ label: "プライバシーポリシー", href: "/privacy" },
						]}
					/>
					<main className="flex-grow">
						{children}
					</main>
					<Footer />
				</div>
			</body>
		</html>
	);
}
